### ISSUE TITLE
第60行 me.$domDown = $('.'+me.opts.domDown.domClass);

### ISSUE THREAD

**Issue by langq235** [ximan/dropload#36]
感觉应该写成
me.$domDown = me.$element.find('.'+me.opts.domDown.domClass);

**Comment by ximan** [comment]
感谢你的提问。
因为页面只会有一个domDown，所以我直接声明了，没有你这种写法严谨，算是偷懒了吧😉

**Comment by januslo** [comment]
我怀疑这个写法会到导致 $downup有机会找不到。我自己的app在后台建立了前端错误的监控，在微信环境下偶然会出现以下错误：
`
 stack=TypeError: Cannot read property 'css' of undefined
    at fnTransition (http://www.shuzhiapp.com/app/lib/dropload/dropload.js:305:12)
    at fnTouchend (http://www.shuzhiapp.com/app/lib/dropload/dropload.js:187:13)
    at HTMLDivElement.<anonymous> (http://www.shuzhiapp.com/app/lib/dropload/dropload.js:110:17)
    at HTMLDivElement.dispatch (http://www.shuzhiapp.com/app/lib/jquery/jquery.min.js:5:14129)
    at HTMLDivElement.v.handle (http://www.shuzhiapp.com/app/lib/jquery/jquery.min.js:5:10866)
`
